### ISSUE TITLE
Feature for Custom Standalone (M3) Control Node

### ISSUE THREAD

**Issue by rdagher** [iot-lab/iot-lab-gateway#55]
Hello,

I have created a [gist](https://gist.github.com/rdagher/0adb14208a906f812eb7b7076b02b12a) and a [fork](https://github.com/rdagher/iot-lab-gateway/tree/stalone_cn_m3) for using the Docker image with **custom** control node, in this case a standalone M3 is used as a standalone control node just capable of sniffing the traffic.
Note that the fork is several commits behind master and some bugs were encountered in the control node native interface (wrapped by python classes). A test script is also available...

Best,
Roudy

**Comment by rienafairefr** [comment]
Looks interesting.
- Can you push a pull request so we can see the differences ?
- In the code, looks like you're using the docker-run, but recently we've migrated to the Makefile (target `make run`), which is much easier than the docker-run script. Maybe rebase on our master and see that (we've updated the documentation)

**Comment by rdagher** [comment]
Well while I was validating this, modifications were being made in the maser regarding the docker run. I will make a pull request so you can test this and then update with the new strategy.
