### ISSUE TITLE
quota for OML log files

### ISSUE THREAD

**Issue by schrein** [iot-lab/iot-lab-gateway#66]
Currently, the iot-lab-gateway produces oml log files for experiment monitoring (e.g. energy consumption, radio level, etc) with uid and gid **senslabeh** . These permissions bypass users quotas (2GB per user) based on unix group **senslab** . Furthermore, logs could use a lot of space (dozen of GB) and could quickly fill all the disk.

**Comment by rienafairefr** [comment]
As an example, running `du -h --threshold=10G /senslab/users | sort -h` on lille's srvssh gives me these users with >10G:

```
22G  kietzman
57G  onur
101G pope
113G nassar
```
jad (nassar) from FUN team was using the platform consumption tracking massively for a paper submission, and with a hundred meg OML file per node, it quickly gets out of hand

Possible options (not judging whether these are good):

* Clean up the files in .iot-lab/<experiment_id> something like a week after the experiment
* Handle the quota per-directory somehow
* Somehow write in .iot-lab as the user
* Use something completely different for pushing the consumption/sniffer/logs 'upstairs" to srvssh from the gateway, without NFS

**Comment by schrein** [comment]
Proposals : 

* if exp data logs > 2GB : lifetime 1 month, next deleted
* All exp data logs expired after 6 months

TODO 

* write python script with crontab/email notification.
* update charter
* update info in monitoring tutorial

**Comment by rienafairefr** [comment]
cf [iot-lab-dev #104](https://github.com/iot-lab/iot-lab-dev/pull/104) for the implementation of the first step
