### ISSUE TITLE
firefly firmware update

### ISSUE THREAD

**Issue by rienafairefr** [iot-lab/iot-lab-gateway#88]
There is an intermittent issue with firefly firmware updates, which I can't yet pinpoint I'm adding it here to remember working on it and if someone has some idea

- Initial (start experiment) flash works fine
- flashing a firmware during an experiment sometimes work sometimes fails with `ERROR: Timeout waiting for ACK/NACK after 'Synch (0x55 0x55)'`
- sometimes, but not always, power cycling the node (stop_dc_on/start_dc_on) permits to flash the wanted firmware

it's frustrating :-(

**Comment by aabadie** [comment]
Could it be that you need to stop the serial redirection before flashing and restart it after ? The cc2538-bsl tool is using the same serial connection to flash and access the UART of the MCU. Maybe there's interference between the socat daemon and the flashing process ?

**Comment by rienafairefr** [comment]
hadn't thought of that, that's certainly possible.
It doesn't look like there is an integration test for that (flashing a firmware during an expe), maybe I'm wrong ?

**Comment by aabadie** [comment]
I think so, the test_simple_experiment does that (at least in _check_debug the idle firmware is flashed while the experiment is running)

**Comment by rienafairefr** [comment]
ok, I'll add a firefly to the integration tests on CI as well

**Comment by aabadie** [comment]
>  I'll add a firefly to the integration tests on CI as well

That would be super nice to have this as well :) But test it a bit manually before activating it in the CI. Using install_lib:
```
fab dev:custom_ids=<custom_id_of_firefly> nodes.test_gateway_code -H root@devlille.iot-lab.info:2222
```

**Comment by rienafairefr** [comment]
There was a ci firefly at some point and integration tests were passing. Probably something regressed :-| The opennode was moved to another place at some point I don't remember why. We got new nodes in the meantime so it's going to be OK

**Comment by aabadie** [comment]
@rienafairefr, I'm closing this ~PR~ issue as I think it's fixed now. Feel free to reopen if it's not the case.
